**An Example**

In [1]:
import numpy as np

In [10]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### The Basics

In [11]:
a.shape

(3, 5)

In [12]:
a.ndim

2

In [14]:
a.dtype.name

'int32'

In [15]:
a.itemsize


4

In [16]:
a.size

15

In [17]:
type(a)

numpy.ndarray

### Array Creation

In [19]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [20]:
a.dtype

dtype('int32')

In [21]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## This is Learning Numpy From Data Analyst

In [23]:
my_list = [1, 2, 3, 4]

In [24]:
my_array1 = np.array(my_list)

In [25]:
my_array1

array([1, 2, 3, 4])

In [26]:
my_list2 = [11, 22, 33, 44]

In [27]:
my_lists = [my_list, my_list2]

In [28]:
my_array2 = np.array(my_lists)

In [29]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
my_zeros_array = np.zeros(5)

In [36]:
my_zeros_array.dtype

dtype('float64')

In [37]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.empty(5)

array([1.15300544e-311, 2.16847421e-028, 1.02263782e-312, 0.00000000e+000,
       0.00000000e+000])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])