In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:] = 99

In [12]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[1]

array([20, 25, 30])

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[1][0]

20

In [35]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [36]:
arr_2d[2]

array([35, 40, 45])

In [37]:
arr2d = np.zeros(100)
arr2d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
# arr_length = arr2d.shape[1]

In [39]:
for i in range(arr2d):
    arr2d[i]=i

TypeError: only integer scalar arrays can be converted to a scalar index