In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
a = np.random.randn(10)
a

array([-1.1061173 , -0.45563736,  1.45466462,  1.40969621,  0.24679219,
       -0.58062288,  0.87005705, -0.87743687,  0.14047771, -1.32063112])

In [10]:
b = np.random.rand(10)
b

array([0.28993111, 0.64217648, 0.94995998, 0.45766003, 0.3433019 ,
       0.36031163, 0.53103786, 0.54296941, 0.06000917, 0.11634799])

In [11]:
# Binary Functions
np.add(a,b)

array([-0.81618619,  0.18653912,  2.40462461,  1.86735624,  0.59009409,
       -0.22031125,  1.40109491, -0.33446745,  0.20048687, -1.20428313])

In [12]:
np.maximum(a,b)

array([0.28993111, 0.64217648, 1.45466462, 1.40969621, 0.3433019 ,
       0.36031163, 0.87005705, 0.54296941, 0.14047771, 0.11634799])